# Generated by Django 5.2.5 on 2025-08-07 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="addnewtrainer",
            name="subject",
            field=models.CharField(default="Math", max_length=100),
        ),
        migrations.AlterField(
            model_name="addnewtrainer",
            name="image",
            field=models.ImageField(upload_to="trainer_images/"),
        ),
        migrations.AlterField(
            model_name="addnewtrainer",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
